### ISSUE TITLE
Pulling tariff information 

### ISSUE THREAD

**Issue by pete-leese** [unlobito/ha-hildebrandglow#49]
How do we get tariff information via this integration?

I can see in the bright app this is available as shown below following the installation of the GlowStick  

![56CF86F5-736C-4C59-B65C-9960068AE5E3](https://user-images.githubusercontent.com/2682742/150585831-d9f1fa8e-b35c-47c3-8a28-73c5b3694469.jpeg)

**Comment by craigmcgowan** [comment]
Hi,

If you see the other issue youve posted about today - https://github.com/unlobito/ha-hildebrandglow/issues/47 - youll notice I have had the same experiences as you. Im using the DCC integration to get this information instead.https://github.com/HandyHat/ha-hildebrandglow-dcc

**Comment by pete-leese** [comment]
Nice one @craigmcgowan suppose it is better than nothing! :)

would you mind posting screenshot of what you configured in HA in terms of which entities you are using please to configure energy? 

Got anything else set up using metrics from this?

**Comment by craigmcgowan** [comment]
Sure...

So from this integration im only pulling in the power consumption. Other two entities (the dodgy energy consumption and non-working gas consumption I have disabled)

![image](https://user-images.githubusercontent.com/40320690/150606937-e68e0ca0-f2cb-4428-97a1-bc1f48ea3150.png)

In the aforementioned handyhat fork integration then, I have 4 devices - 2 x electric meters and 2 x gas meters. This matches the "devices" in the Android App too. Im not sure why they are duplicated - they werent until I installed by glow stick today.

So ive disabled the entities from the two duplicate devices, and for gas an electric ive got pretty much the same entites.

![image](https://user-images.githubusercontent.com/40320690/150607900-060270ac-71f7-4a7d-8883-8fc37501f912.png)

In the Home Assistant Energy then - ive just used the yearly energy feed (I think this is correct) and the rate.

![image](https://user-images.githubusercontent.com/40320690/150608055-1820fef0-815a-4694-aff2-ed2d6ee8dcbc.png)

This is mirrored for both Gas and Electric.

Ive then made a template sensor to work out the current cost per hour of the electric im using, which is shown my own lovelace view in case its of interest by the gauge.

![image](https://user-images.githubusercontent.com/40320690/150608364-a234ce94-937a-4c2a-8ddd-c732641252cb.png)

The code for this is below.
```
  - platform: template
    sensors:
      power_consumption_price:
        friendly_name: "Power Consumption - Price"
        unit_of_measurement: "£"
        value_template: >-
          {{ ((states('sensor.glow_power_consumption') | float / 1000 * (states('sensor.electric_tariff_rate') | float)) + ((states('sensor.electric_tariff_standing')| float) / 24))| round(2) }}

```

As a note - its correct that I havent used any Gas today - this isnt an error with any integration - it matches my Bright app data

Let me know if youd like to see anything else!

Have a good weekend!
